### ISSUE TITLE
After six downloads the plugin stops working

### ISSUE THREAD

**Issue by reschandreas** [TUM-Dev/lecture-download#1]
If you need to download several videos at once after six downloads the plugin doesn't start another one, only solution is closing chrome and restarting it.

**Comment by lukaskollmer** [comment]
sorry for the late response, i only just saw your issue.

i looked into this and this seems to be a limitation by chrome. if i click the download button many times, chrome seems to only allow four simultaneous downloads. once a download finishes or is cancelled, a new one starts, until all initiated downloads are finished.

so even if you start multiple downloads and they don't all immediately appear in `chrome://downloads`, chrome still seems to queue them and will download them all eventually.

i don't think there is anything i can do about this
