### ISSUE TITLE
doesn't seem to work?

### ISSUE THREAD

**Issue by katterfide** [TUM-Dev/lecture-download#2]
Hello, little to no coding/dev experience here.
First time using, it doesnt seem to work for me; the download button.
Maybe the issue is the new windows update?
thank you so much :)

**Comment by lukaskollmer** [comment]
which lecture are you trying to download?

**Comment by katterfide** [comment]
https://streams.tum.de/Mediasite/Play/aade81cdf80d484593c0876cf5cb01121d?catalog=03fd1c7e-ee08-4ee3-a9a0-e6b40bc6f593

"Mathe Vorkurs"

**Comment by lukaskollmer** [comment]
Works fine for me. You may have to wait a couple of seconds before clicking the Download button

**Comment by katterfide** [comment]
not quite there yet. 
Tried restarting also..
Thank you for your help anyway :))

**Comment by lukaskollmer** [comment]
Can you do either of the following:
- open the extension
- wait 10 seconds
- click download
- wait another 5 seconds
- right-click the extension window
- select "Inspect"
- click "Console" at the top of the new window that just opened
- look if there's some error message in the log

OR
-

**Comment by katterfide** [comment]
the inspect popup console provides me with this every time;

popup.html:1 
Error handling response: TypeError: Cannot read property 'name' of undefined
    at chrome-extension://jlbncgdbgjgdimjnihmniommnbhddajf/dl_streams.tum.js:30:89

and once I click on download it conjures up another error;

popup.js:63 
Uncaught TypeError: Cannot read property 'length' of null
    at HTMLButtonElement.<anonymous> (popup.js:63)

**Comment by lukaskollmer** [comment]
Thanks! Which version of Chrome are you using?

**Comment by katterfide** [comment]
Version 77.0.3865.90 (Official Build) (64-bit)

however as soon as I went to check it started to update itself, so now I'm on

Version 77.0.3865.120 (Official Build) (64-bit)

I even restarted my laptop but the same errors are still showing up.

**Comment by lukaskollmer** [comment]
Hmm ok I still can't manage to reproduce this, I'll take a closer look at the weekend.

Are there any other error messages in the extension inspector's console?

**Comment by katterfide** [comment]
Hello Lukas,
My lectures have fully started now and I've decided to try the download feature again.
Somehow it worked. I merely updated chrome and nothing else.
The issue seems to have resolved itself :))
Thanks for your patience and time.
Felix
