### ISSUE TITLE
Some Lectures don't work.

### ISSUE THREAD

**Issue by Dekuguy** [TUM-Dev/lecture-download#4]
In DS all lecture works except these 2:

- https://streams.tum.de/Mediasite/Play/6d65442c358c4452803f1b07e9839e6f1d?catalog=799ca689-c418-424f-8722-785d4e35cca6
- https://streams.tum.de/Mediasite/Play/7e546ac66e3f47e39bc8aecb8fc764061d?catalog=799ca689-c418-424f-8722-785d4e35cca6

Lecture Overview:
- https://streams.tum.de/Mediasite/Catalog/catalogs/ds-2019_20

Why is that?

**Comment by lukaskollmer** [comment]
You'll have to change the filename. By default it uses the title  of the lecture (in this case `Diskrete Strukturen_015 Syxntax_ Formationsregeln - "Syntaktischer Zucker"`). Chrome will refuse to download the file if the name contains letters it doesn't like.

If it change it to something simple like `DS15` it works fine
